"""Criando tabelas

Revision ID: 5d1cc31f0f2c
Revises: 
Create Date: 2026-04-01 21:12:47.852346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1cc31f0f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raridade',
    sa.Column('idRaridade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('idRaridade')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('item',
    sa.Column('idItem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idRaridade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descr', sa.String(length=120), nullable=False),
    sa.Column('imagem_url', sa.String(length=100), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idRaridade'], ['raridade.idRaridade'], ),
    sa.PrimaryKeyConstraint('idItem')
    )
    op.create_table('inventario_item',
    sa.Column('idInventarioItem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idItem', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idItem'], ['item.idItem'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idInventarioItem')
    )
    op.create_table('hotbar',
    sa.Column('idHotbar', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idInventarioItem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idInventarioItem'], ['inventario_item.idInventarioItem'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idHotbar'),
    sa.UniqueConstraint('idUsuario', 'idInventarioItem', name='uq_usuario_inventario_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotbar')
    op.drop_table('inventario_item')
    op.drop_table('item')
    op.drop_table('usuario')
    op.drop_table('raridade')
    # ### end Alembic commands ###
